### PR TITLE
readability of `plant_crafts.lua`

### PR DESCRIPTION
**Pull request by OCRenkist**

### CODE REVIEW

**Comment by jeremyshannon** [comment]
Can you configure whatever you're using to format the code to place end statements on the same column as the if/else/do/etc statement that opened the code block? Having them indented to the right looks wrong to me and potentially confusing in a multi-level code block.
 Alternately, perhaps we should adopt an automated code styler and pass everything but the data tables through it.

**Comment by OCRenkist** [comment]
Placing `end` statements at the same indent level as their block-opening statement, breaks the code-folding functionality in every Lua editor of which I’m aware. Instead of being while folded 
> :heavy_plus_sign: function name1(args)
> :heavy_plus_sign: function name2(args)
> :heavy_plus_sign: function name3(args)

it becomes
> :heavy_plus_sign: function name1(args)
>  &nbsp;&nbsp;&nbsp; end
> :heavy_plus_sign: function name2(args)
>  &nbsp;&nbsp;&nbsp; end
> :heavy_plus_sign: function name3(args)
>  &nbsp;&nbsp;&nbsp; end

in other words, lots of lines with nothing but `end` statements on them, even when the code is folded.

**Comment by jeremyshannon** [comment]
That's weird. Everybody in the Minetest community does it the second way as far as I've seen. I guess nobody uses Visual Studio?

**Comment by OCRenkist** [comment]
I get the same effect in `Sublime Text` and various tutorial websites. If anything, `Visual Studio` and `Eclipse`, when writing `Java` and `C++`, are the only editors in which I have seen this problem **not** occur.

**Pull request closed without merging**
