### PR TITLE
group nodes logically rather than alphabetically

### PR DESCRIPTION
**Pull request by OCRenkist**
Aiming to sort roughly by technology level, with various cosmetic nodes listed at the end.

### CODE REVIEW

**Comment by jeremyshannon** [comment]
Trouble with this is, this is auto-generated. If I alter/add nodes and regenerate, all this work will be overwritten.

**Comment by OCRenkist** [comment]
Would you prefer to have two separate files? One for auto-generated alphabetical listing, and one for curated tech-level listing. That would free you to auto-generate again without having the responsibility to differentiate and place the new lines at the end of the tech-level listing for me or others to sort.

**Comment by jeremyshannon** [comment]
That seems like an eminently reasonable idea.

**Comment by OCRenkist** [comment]
Should be ready for you to `pull`. 👍

**Pull request merged**
