### PR TITLE
Bones improvement

### PR DESCRIPTION
**Pull request by OCRenkist**

### CODE REVIEW

**Comment by jeremyshannon** [comment]
Looks like it's still indenting end statements to the right of the entry point. Maybe leave out the copyediting, and we can perhaps look into automated styling.

**Comment by OCRenkist** [comment]
I figured you might say that, so I did two separate `commit` actions — are you able to accept one and discard the other? 

Also: Copyediting is what we want, we just have yet to arrive at an agreed-upon manual of style. :-)

**Comment by jeremyshannon** [comment]
Nope, I'd have to merge the branch and then revert the unwanted commit. Easier if you revert and I just squash merge what's left.

**Comment by jeremyshannon** [comment]
Bump. If you can "git revert b91568c" and push that up, I'll get this folded in.

**Comment by OCRenkist** [comment]
Reverted. 👍 I am also working with the developer of https://github.com/zokugun/vscode-explicit-folding to acheive the desired visual effect.

**Pull request merged**
